export const port = 'http://localhost:3000';
export const customer = '/user';
export const login = '/login';
export const search = '/search';
export const query = '?query=';
export const movie = '/movie';
export const rental = '/rental';
export const searchEmail = '/email';
export const update = '/update';