export const port = 'https://fakeflix-backend.herokuapp.com';
export const customer = '/user';
export const login = '/login';
export const search = '/search';
export const query = '?query=';
export const movie = '/movie';
export const rentals = '/rental';
export const searchEmail = '/email';
export const update = '/update';